issues/urls.py
from django.urls import path
from . import views

app_name = 'issues'

urlpatterns = [
    path('create', views.create_issue, name='create'),
    path('<str:owner>/<str:repository>/<int:number>', views.show_issue, name='show'),
    path('<str:owner>/<str:repository>/<int:number>/rate', views.rate, name='rate'),
]

iwannacontrib/urls.py
from django.contrib import admin
from django.urls import path, include

from triage.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('issues/', include('issues.urls', namespace='issues')),
    path('', home, name='home')
]

issues/models.py
import markdown
from django.db import models
from django.urls import reverse

from triage.models import ProgrammingLanguage, IssueRate, COMPLEXITY_LEVEL


class Owner(models.Model):
    owner = models.CharField(max_length=200, primary_key=True, null=False)


class Repository(models.Model):
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE, null=False)
    name = models.CharField(max_length=200, null=False)

    class Meta:
        unique_together = (("owner", "name"),)


class Issue(models.Model):
    repository = models.ForeignKey(Repository, null=False, on_delete=models.CASCADE)
    number = models.IntegerField(null=False)
    name = models.CharField(max_length=200)
    body = models.TextField()
    state = models.CharField(max_length=60)
    main_language = models.ForeignKey(
        ProgrammingLanguage,
        on_delete=models.CASCADE,
    )
    current_rate = models.ForeignKey(IssueRate, null=True, default=None, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (("repository", "number"),)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def get_url(self) -> str:
        return reverse("issues:show", kwargs={
            "owner": self.repository.owner.owner,
            "repository": self.repository.name,
            "number": self.number
        })

    def get_rate_url(self) -> str:
        return reverse("issues:rate", kwargs={
            "owner": self.repository.owner.owner,
            "repository": self.repository.name,
            "number": self.number
        })

    def get_repository_name(self) -> str:
        return f'{self.repository.owner.owner}/{self.repository.name}'

    def get_owner_avatar(self):
        return f'https://github.com/{self.repository.owner.owner}.png?size=24'

    @property
    def rate_label(self):
        if self.current_rate is None:
            return 'Not rated yet'

        return self.current_rate.get_rate_display()

    @property
    def html(self):
        return markdown.markdown(self.body, extensions=['fenced_code'])

    @property
    def external_url(self):
        return f'https://github.com/{self.repository.owner.owner}/{self.repository.name}/issues/{self.number}'

    def rate(self, rate_number: int):
        rate = IssueRate.objects.get_or_create(rate=rate_number)[0]
        issue_rate = IssueRateRel.objects.create(issue=self, rate=rate)
        self.rates.add(issue_rate)

        self.current_rate = IssueRate.objects.get_or_create(
            rate=round(self._calculate_rate_sum() / self._total_rates())
        )[0]

    def _calculate_rate_sum(self) -> int:
        total = 0

        for rate in self.rates.all():
            total += rate.rate.rate

        return total

    def _total_rates(self) -> int:
        return len(self.rates.all())


class IssueRateRel(models.Model):
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE, related_name='rates')
    rate = models.ForeignKey(IssueRate, on_delete=models.CASCADE)

triage/models.py
from django.db import models


class ProgrammingLanguage(models.Model):
    name = models.CharField(max_length=200, null=False, unique=True)

    def __str__(self):
        return self.name

    @property
    def link(self):
        return f'/?language={self.name}&rate=all#search-section-form'

    @staticmethod
    def get_other_default_language():
        return ProgrammingLanguage.objects.get_or_create(name='Other')[0]


COMPLEXITY_LEVEL = [
    (1, 'Very Easy'),
    (2, 'Easy'),
    (3, 'Medium'),
    (4, 'Hard'),
    (5, 'Very Hard'),
]


class IssueRate(models.Model):
    rate = models.IntegerField(choices=COMPLEXITY_LEVEL)

issues/forms.py
from django import forms
from django.core.exceptions import ValidationError

from issues.services.create_issue_service import IssueToBeCreated, InvalidGithubUrlException


class GithubUrlField(forms.Field):
    def to_python(self, value):
        if not value:
            return
        try:
            return IssueToBeCreated(value)
        except InvalidGithubUrlException as e:
            raise ValidationError(f"It must be a Github issue URL. Found: {e.url}")


class CreateIssueForm(forms.Form):
    url = GithubUrlField(required=True, label="Github Issue URL")

triage/forms.py
from django import forms

from issues.models import Issue
from triage.models import ProgrammingLanguage, COMPLEXITY_LEVEL

COMPLEXITY_LEVEL_WITH_EMPTY = [
    (None, 'Not Rated'),
    ('all', 'All Rates')
] + COMPLEXITY_LEVEL


class SearchForm(forms.Form):
    language = forms.ModelChoiceField(queryset=ProgrammingLanguage.objects.all(), to_field_name='name', required=True)
    rate = forms.ChoiceField(choices=COMPLEXITY_LEVEL_WITH_EMPTY, required=False, label="Difficult Level", initial='all')

    @property
    def results(self):
        if not self.is_valid():
            return Issue.objects.all().order_by('-created_at')[:20]

        rate = self._get_rate()

        query = dict(
            main_language=self.cleaned_data.get('language'),
        )

        if rate != 'all':
            query.update(current_rate__rate=rate)

        return Issue.objects.filter(**query).order_by('-created_at')[:1000]

    @property
    def search_title(self):
        if not self.is_valid():
            return 'Be a contributor to open source'

        language = self.cleaned_data.get('language')
        return f'Let me contrib with {language} to Open Source'

    @property
    def search_meta_description(self):
        if not self.is_valid():
            return 'Find an issue that is perfect with your skills and contribute to open source projects.'

        language = self.cleaned_data.get('language')
        return f'Find an {language} issue that is perfect with your skills and contribute to open source projects.'

    def _get_rate(self):
        rate = self.cleaned_data.get('rate')

        if not rate:
            return None

        return rate

issues/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from github import Github

from issues.forms import CreateIssueForm
from issues.models import Issue
from issues.services.create_issue_service import CreateIssueService


def create_issue(request):
    form = CreateIssueForm()

    if request.method == 'POST':
        form = CreateIssueForm(request.POST)

        if form.is_valid():
            issue = CreateIssueService().create_issue(Github(), form.cleaned_data.get('url'))
            return redirect(issue.get_url())

    return render(request, 'issues/create_issue.html', {
        "form": form
    })


def show_issue(request, owner: str, repository: str, number: int):
    issue = Issue.objects.get(
        repository__owner__owner=owner,
        repository__name=repository,
        number=number
    )

    return render(request, 'issues/show_issue.html', {
        "issue": issue
    })


def rate(request, owner: str, repository: str, number: int):
    issue = Issue.objects.get(
        repository__owner__owner=owner,
        repository__name=repository,
        number=number
    )

    issue.rate(int(request.POST['rate']))
    issue.save()

    messages.add_message(request, messages.SUCCESS, 'You vote has been registered. Thank you for voting.')

    return redirect(issue.get_url())

triage/views.py
from django.shortcuts import render

from triage.forms import SearchForm


def home(request):
    form = SearchForm()

    if request.GET.get('language'):
        form = SearchForm(request.GET)

    return render(request, 'triage/home.html', {
        "form": form,
    })

issues/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <meta name="description" content="{% block meta_description %}{% endblock %}">

    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@100;400;700&display=swap" rel="stylesheet">

    <title>{% block page_title %}{% endblock %} | Contrib World</title>

    <style>
        body {
            padding: 85px 0 0 0;
            margin: 0;
            font-family: "Raleway", Verdana, Arial, sans-serif;
        }

        .main-header {
            background: #038C73;
            position: fixed;
            width: 100%;
            line-height: 65px;
            top: 0;
            left: 0;
        }

        .main-header .header-content {
            display: flex;
            justify-content: space-between;
        }

        .main-header a.home_link {
            color: #ffffff;
            font-weight: 700;
            text-decoration: none;
        }

        a.publish_issue {
            text-decoration: none;
            color: #ffffff;
            border-radius: 20px;
            padding: 5px 15px;
            background: #04BF9D;
        }

        a.publish_issue.publish_issue_big {
            font-size: 20px;
            padding: 15px 35px;
            border-radius: 100px;
            display: inline-block;
            font-weight: normal;
        }

        .center-content {
            margin: 0 auto;
            max-width: 1024px;
            padding: 0 20px;
        }

        .issue-rate- {
            background: #F0F0F2;
        }

        .issue-rate-1 {
            background: #00BF54;
        }

        .issue-rate-2 {
            background: #008359;
        }

        .issue-rate-3 {
            background: #FFDE4B;
        }

        .issue-rate-4 {
            background: #EF434D;
        }

        .issue-rate-5 {
            background: #BE1846;
        }

        .issue-title h2 {
            margin: 0;
            font-size: 14px;
            font-weight: 100;
            display: flex;
            align-items: center;
        }
        .issue-title h2 img {
            margin-right: 10px;
        }
        .issue-title h1 {
            margin: 10px 0 0 0;
            font-weight: 400;
        }

        .issue-title h1 span {
            text-decoration: none;
            padding: 5px 10px;
            display: inline-block;
            font-size: 60%;
        }

        .issue-title h1 span.issue-number {
            background: #F0F0F2;
        }

        .issue-title h1 span.issue-language {
            background: #e45686;
        }

        .issue-title a {
            color: #000000;
            text-decoration: none;
        }

        .messages {
            background: #00c39b;
            margin: -20px 0 40px;
            line-height: 48px;
            list-style: none;
            text-align: center;
        }
    </style>
</head>
<body>
    <header class="main-header">
        <div class="center-content header-content">
            <a href="{% url 'home' %}" class="home_link">
                Contrib World
            </a>

            <div>
                <a href="{% url 'issues:create' %}" class="publish_issue">Publish an Issue</a>
            </div>
        </div>
    </header>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="center-content">
        {% block main_content %}
        {% endblock %}
    </div>

    {% block after_main_content %}
    {% endblock %}

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-86898401-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-86898401-2');
    </script>

</body>
</html>

issues/templates/issues/create_issue.html
{% extends 'base.html' %}

{% block page_title %}Ask for help by publishing an issue{% endblock %}
{% block meta_description %}Do you need contributors to you project? Publish your issue we will help you to share it thought our platform!{% endblock %}

{% block main_content %}
    <style>

        .section-box {
            margin-top: 20px;
            background: #F0F0F2;
            padding: 20px;
            border-radius: 20px;
            display: flex;
            min-width: 190px;
            flex-direction: column;
            justify-content: space-between;
        }

        .section-box h3 {
            margin: 0;
        }

        .form-content {
            display: flex;
            flex-direction: column;
            max-width: 500px;
        }

        .errorlist {
            color: #F44336;
        }

        .create-form label {
            margin-bottom: 10px;
        }
        .create-form input {
            border: 1px solid #ccc;
            padding: 15px;
            background: #ffffff;
            border-radius: 10px;
        }
        .create-form .button {
            border: 0;
            padding: 15px;
            border-radius: 10px;
            color: #ffffff;
            background: #04BF9D;
            box-shadow: 0 0 5px rgba(255, 255, 255, 0.2);
            transition: all 0.5s;
            width: 100%;
            margin-top: 10px;
        }
    </style>

    <div class="">
        <h1>Do you need contributors to you project?</h1>

        <p>Just past an issue URL above and we will help you to share it thought our platform!</p>
    </div>

    <form action="{% url "issues:create" %}" method="post" class="section-box create-form">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="button" value="Submit">
    </form>
{% endblock %}

issues/templates/issues/partials/issue_title.html
<hgroup class="issue-title">
    <h2>
        <img src="{{ issue.get_owner_avatar }}" alt="">
        {{ issue.get_repository_name }}
    </h2>
    <h1>
        <a href="{{ issue.get_url }}">
            <span class="issue-language">{{ issue.main_language }}</span>
            <span class="issue-rate issue-rate-{{ issue.current_rate.rate }}">{{ issue.rate_label }}</span>
            <span class="issue-number">#{{ issue.number }}</span>
            {{ issue.name }}
        </a>
    </h1>
</hgroup>

issues/templates/issues/show_issue.html
{% extends 'base.html' %}

{% block page_title %}Contrib to a {{ issue.main_language }} issue: {{ issue.name }}{% endblock %}
{% block meta_description %}The Python repository {{ issue.repository.name }} needs your help. Contribute to {{ issue.name }}.{% endblock %}

{% block main_content %}
    <style>
        #issue-body img {
            max-width: 100%;
        }
        #issue-body code {
            background: #F0F0F2;
            padding: 2px 4px;
        }
        #issue-body pre {
            background: #F0F0F2;
            padding: 20px;
            display: block;
            overflow: auto;
        }
        #issue-body pre code {
            padding: 0;
        }

        .section-box {
            margin-top: 20px;
            background: #F0F0F2;
            padding: 20px;
            border-radius: 20px;
            display: flex;
            min-width: 190px;
            flex-direction: column;
            justify-content: space-between;
        }

        .section-box h3 {
            margin: 0;
        }

        .section-box .buttons {
            margin-top: -10px;
        }

        .action-button {
            border: 0;
            padding: 10px 20px;
            border-radius: 10px;
            color: #ffffff;
            margin-top: 10px;
            box-sizing: border-box;
        }

        .action-button.go-to-button {
            background: #04BF9D;
            text-decoration: none;
            display: inline-block;
            width: 100%;
        }


        #action-section {
            display: grid;
            grid-template-columns: 1fr 1fr 1fr;
            grid-gap: 20px;
            overflow: auto;
        }
    </style>
    <article>
        <header class="issue-header">
            {% include "issues/partials/issue_title.html" %}
        </header>

        <div id="action-section">
            <section class="section-box solve-section">
                <div class="content">
                    <h3>I can solve this issue!</h3>

                    <p>If you believe that you can help to solve this issue go to repository and start to interact with the maintainers.</p>
                </div>

                <div class="buttons">
                    <a href="{{ issue.external_url }}" class="action-button go-to-button" target="_blank">Go to repository</a>
                </div>
            </section>

            <form method="post" action="{{ issue.get_rate_url }}" id="rate-form" class="section-box">
                <div class="content">
                    {% csrf_token %}
                    <h3>Rate the issue complexity</h3>

                    <p>By rating an issue you'll help others to find and solve this issue.</p>
                    <p>How complex is to solve this issue?</p>
                </div>
                <div class="buttons">
                    <button name="rate" class="action-button issue-rate-1" value="1" title="Rate as Very Easy">Very Easy</button>
                    <button name="rate" class="action-button issue-rate-2" value="2" title="Rate as Easy">Easy</button>
                    <button name="rate" class="action-button issue-rate-3" value="3" title="Rate as Medium">Medium</button>
                    <button name="rate" class="action-button issue-rate-4" value="4" title="Rate as Hard">Hard</button>
                    <button name="rate" class="action-button issue-rate-5" value="5" title="Rate as Very Hard">Very Hard</button>
                </div>
            </form>

            <section class="section-box solve-section">
                <div class="content">
                    <h3>More from <span id="main_language">{{ issue.main_language }}</span></h3>

                    <p>I can't solve this issue but I want to see other issues from {{ issue.main_language }}.</p>
                </div>

                <div class="buttons">
                    <a href="{{ issue.main_language.link }}" class="action-button go-to-button">All {{ issue.main_language }} issues</a>
                </div>
            </section>
        </div>

        <section>
            <h2>Description</h2>
            <div id="issue-body">
                {{ issue.html | safe }}
            </div>
        </section>
    </article>
{% endblock %}

triage/templates/triage/home.html
{% extends 'base.html' %}

{% block page_title %}{{ form.search_title}}{% endblock %}

{% block meta_description %}{{ form.search_meta_description }}{% endblock %}

{% block main_content %}
    <style>
    .main-home {
        margin: 20px 0 40px;
    }
    .main-home h2 {
        margin: 0;
        font-size: 20px;
    }
    .main-home h1 {
        font-weight: 100;
        margin: 0;
    }

    .how-to {
        display: grid;
        grid-template-columns: 1fr 1fr 1fr;
        grid-gap: 20px;
        margin-top: 20px;
        overflow: auto;
    }

    .how-to-description {
        background: #F0F0F2;
        padding: 20px;
        border-radius: 20px;
        min-width: 150px;
    }

    .how-to-description h3 {
        font-size: 100%;
    }

    .how-to-description p {
        line-height: 24px;
    }

    #search-section {
        background: #242524;
        color: #ffffff;
        padding: 40px 20px;
    }

    #search-section .center-content {
        display: grid;
    }

    #search-section h1 {
        font-weight: 100;
        text-align: center;
        padding-bottom: 20px;
        border-bottom: 1px solid #333635;
        margin: 0 0 30px 0;
    }

    #search-section form {
        display: grid;
        grid-template-columns: 1fr auto;
        grid-gap: 20px;
        align-items: center;
    }

    #search-section-form {
        display: grid;
        grid-template-columns: auto 2fr auto 2fr;
        grid-gap: 20px;
        align-items: center;
    }

    #search-section-form select {
        border: 1px solid #ccc;
        padding: 15px;
        background: #ffffff;
        border-radius: 10px;
    }

    #search-section button {
        border: 0;
        padding: 15px;
        border-radius: 10px;
        background: rgba(255, 255, 255, 0.5);
        box-shadow: 0 0 5px rgba(255, 255, 255, 0.2);
        transition: all 0.5s;
        width: 100%;
    }

    #search-section button:hover {
        background: rgba(255, 255, 255, 0.7);
        box-shadow: 0 0 5px rgba(255, 255, 255, 0.5);
    }

    #result {
        margin: 40px 0;
    }

    .result-item {
        padding: 20px 0;
        border-bottom: 1px solid #F0F0F2;
    }

    .publish_issue_section {
        padding: 45px 0 0 0;
        text-align: center;
        font-size: 20px;
        font-weight: 100;
    }

    @media screen and (max-width: 800px){
        #search-section-form {
            grid-template-columns: 1fr;
        }
        #search-section form {
            grid-template-columns: 1fr;
        }
    }
    </style>

    <main class="main-home">
        <hgroup>
            <h2><u>Contrib World</u> helps you to</h2>
            <h1>match an open source project with your skills</h1>
        </hgroup>

        <section class="how-to">
            <div class="how-to-description">
                <h3>Search an Issue</h3>

                <p>Use the form bellow to search an issue that matches with your coding skills.</p>
            </div>

            <div class="how-to-description">
                <h3>Rate the issue</h3>

                <p>Read and rate the complexity of the issue. That what you'll help others to find the perfect issue to work on.</p>
            </div>

            <div class="how-to-description">
                <h3>Code</h3>

                <p>Did you find the perfect match? Code and help the open source community.</p>
            </div>
        </section>

        <div class="publish_issue_section">
            <p>Do you have an open source project? Publish an issue and get help from others.</p>
            <p><a href="{% url 'issues:create' %}" class="publish_issue publish_issue_big">Publish an Issue</a></p>
        </div>
    </main>
{% endblock %}

{% block after_main_content %}
    <section id="search-section">
        <div class="center-content">
            <h1>Search for an issue!</h1>

            <form action="#search-section-form">
                <div id="search-section-form">
                    {{ form }}
                </div>
                <div>
                    <button>Search</button>
                </div>
            </form>
        </div>
    </section>

    <section id="result">
        <div class="center-content">
            {% for issue in form.results %}
                <div class="result-item">
                    {% include "issues/partials/issue_title.html" %}
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}